# Experiment Specific
experiment_name: 'DeepLab_Abdomen_MR_Seg'
data_root: '/media/dell/disk2/zhoujie/MICCAI23-deeplab_TCT/Abdome_data/'
save_root: '/media/dell/disk2/zhoujie/MICCAI23-deeplab_TCT/source_seg'
source_sites:
- 'MR_label_70'
resume_dir: ''
continue_train: False
total_epochs: 100
random_seed: 999
organ_list:
- 'Spleen'
- 'R.Kidney'
- 'L.Kidney'
- 'Liver'

# Dataloader Setting
img_size:
- 256
- 256
batch_size: 16
num_workers: 8

# Model 
arch: 'DeepLab'
use_prototype: False
update_prototype: False
input_dim: 3
feat_dim: 32
output_dim: 256
num_classes: 5

# Optim parameters
lr: 0.0001

# Loss parameters
ce_ignore_index: -1
dice_ignore_index: 0

# display
save_epochs: 10
eval_epochs: 1
display_steps: 100
save_visuals: True

# test
test: False